// <auto-generated />
using System;
using GymAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymAPI.Migrations
{
    [DbContext(typeof(QlPhonggymContext))]
    partial class QlPhonggymContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymAPI.Models.CoSoVatChat", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<double?>("ChiPhiBaoTri")
                        .HasColumnType("float");

                    b.Property<double?>("ChiPhiMua")
                        .HasColumnType("float");

                    b.Property<string>("ChiTietBaoTri")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("NgayBaoTriCuoi")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayHetHanBaoHanh")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuongCsvc")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongCSVC");

                    b.Property<string>("TenSp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenSP");

                    b.Property<string>("TinhTrangCsvc")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TinhTrangCSVC")
                        .HasDefaultValue("Hoạt động", "TinhTrangDefault");

                    b.HasKey("MaSp")
                        .HasName("MaSP_PK");

                    b.ToTable("CoSoVatChat", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.GoiTap", b =>
                {
                    b.Property<string>("MaGoiTap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("GiaTien")
                        .HasColumnType("money");

                    b.Property<string>("LoaiGoitap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenGoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Thoihan")
                        .HasColumnType("int")
                        .HasColumnName("thoihan");

                    b.HasKey("MaGoiTap")
                        .HasName("MaGoiTap_PK");

                    b.ToTable("GoiTap", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.Hlv", b =>
                {
                    b.Property<string>("MaHlv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHLV");

                    b.Property<string>("Chuyenmon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Luong")
                        .HasColumnType("money");

                    b.Property<string>("Sdthlv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDTHLV");

                    b.Property<string>("TenHlv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenHLV");

                    b.HasKey("MaHlv")
                        .HasName("maHLV_PK");

                    b.HasIndex(new[] { "Sdthlv" }, "SDTHLV_Unique")
                        .IsUnique()
                        .HasFilter("[SDTHLV] IS NOT NULL");

                    b.ToTable("HLV", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.Hoadon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<DateOnly?>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())", "NgayThanhToan_Default");

                    b.Property<string>("PhuongThucTt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhuongThucTT");

                    b.Property<int?>("SoLuongHoaDon")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("money");

                    b.HasKey("MaHoaDon")
                        .HasName("MaHoaDon_PK");

                    b.HasIndex("MaHd");

                    b.ToTable("Hoadon", null, t =>
                        {
                            t.HasTrigger("Trg_KichHoatThanhToan");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GymAPI.Models.HoiVien", b =>
                {
                    b.Property<string>("MaHv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maHV");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Gioitinh")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("gioitinh");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sdt");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten");

                    b.Property<string>("Trangthai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Locked", "Trangthai_Default");

                    b.HasKey("MaHv")
                        .HasName("maHV_PK");

                    b.HasIndex(new[] { "Sdt" }, "UQ__HoiVien__DDDFB4830A93463B")
                        .IsUnique()
                        .HasFilter("[sdt] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "emailhv_unique")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("HoiVien", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.HopDong", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaGoiTap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaHv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maHV");

                    b.Property<DateOnly?>("NgayBd")
                        .HasColumnType("date")
                        .HasColumnName("NgayBD");

                    b.Property<DateOnly?>("NgayKt")
                        .HasColumnType("date")
                        .HasColumnName("NgayKT");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1, "SoLuong_Default");

                    b.Property<string>("TrangThaiHd")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TrangThaiHD")
                        .HasDefaultValue("Locked", "TrangThaiHD_Default");

                    b.HasKey("MaHd")
                        .HasName("MaHD_PK");

                    b.HasIndex("MaGoiTap");

                    b.HasIndex("MaHv");

                    b.ToTable("HopDong", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.LichSuXuatBaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<DateTime?>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiXuat")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NoiDungTomTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBaoCao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBaoCao")
                        .HasName("PK__LichSuXu__25A9188C1016F31F");

                    b.HasIndex("NguoiXuat");

                    b.ToTable("LichSuXuatBaoCao", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.LichTap", b =>
                {
                    b.Property<string>("MaLich")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("KhungGioTap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaHlv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHLV");

                    b.Property<string>("MaHv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maHV");

                    b.Property<DateOnly>("NgayTap")
                        .HasColumnType("date");

                    b.HasKey("MaLich")
                        .HasName("MaLich_PK");

                    b.HasIndex("MaHlv");

                    b.HasIndex("MaHv");

                    b.ToTable("LichTap", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNV");

                    b.Property<string>("Chucvu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("chucvu");

                    b.Property<string>("EmailNv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("emailNV");

                    b.Property<string>("HovaTenNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HovaTenNV");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("matkhau")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgaySinhNv")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinhNV");

                    b.Property<string>("Sdtnv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDTNV");

                    b.Property<string>("TenDn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("tenDN")
                        .IsFixedLength();

                    b.HasKey("MaNv")
                        .HasName("maNV_PK");

                    b.HasIndex(new[] { "Sdtnv" }, "SDT_Unique")
                        .IsUnique()
                        .HasFilter("[SDTNV] IS NOT NULL");

                    b.HasIndex(new[] { "EmailNv" }, "email_Unique")
                        .IsUnique()
                        .HasFilter("[emailNV] IS NOT NULL");

                    b.HasIndex(new[] { "TenDn" }, "tenDN_UNIque")
                        .IsUnique()
                        .HasFilter("[tenDN] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.ThongKeHoiVien", b =>
                {
                    b.Property<string>("Gioitinh")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("gioitinh");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("TyLePhanTram")
                        .HasColumnType("decimal(5, 2)");

                    b.ToTable((string)null);

                    b.ToView("ThongKeHoiVien", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.ViewBaoCaoTaiSan", b =>
                {
                    b.Property<double?>("ChiPhiBaoTri")
                        .HasColumnType("float");

                    b.Property<double?>("ChiPhiMua")
                        .HasColumnType("float");

                    b.Property<int?>("SoLuongCsvc")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongCSVC");

                    b.Property<int?>("SoNgayConBaoHanh")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenSP");

                    b.Property<string>("TinhTrangCsvc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TinhTrangCSVC");

                    b.ToTable((string)null);

                    b.ToView("View_BaoCaoTaiSan", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.ViewDoanhThuGoiTap", b =>
                {
                    b.Property<int?>("SoLuongDangKy")
                        .HasColumnType("int");

                    b.Property<string>("TenGoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TongDoanhThu")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("View_DoanhThuGoiTap", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.ViewHieuSuatHlv", b =>
                {
                    b.Property<string>("Chuyenmon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LuongCoBan")
                        .HasColumnType("int");

                    b.Property<string>("MaHlv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHLV");

                    b.Property<string>("TenHlv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenHLV");

                    b.Property<int?>("TongSoBuoiDay")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("View_HieuSuatHLV", (string)null);
                });

            modelBuilder.Entity("GymAPI.Models.Hoadon", b =>
                {
                    b.HasOne("GymAPI.Models.HopDong", "MaHdNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("MaHD_FK");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("GymAPI.Models.HopDong", b =>
                {
                    b.HasOne("GymAPI.Models.GoiTap", "MaGoiTapNavigation")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaGoiTap")
                        .HasConstraintName("maGoi_FK");

                    b.HasOne("GymAPI.Models.HoiVien", "MaHvNavigation")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaHv")
                        .HasConstraintName("maHV_FK");

                    b.Navigation("MaGoiTapNavigation");

                    b.Navigation("MaHvNavigation");
                });

            modelBuilder.Entity("GymAPI.Models.LichSuXuatBaoCao", b =>
                {
                    b.HasOne("GymAPI.Models.NhanVien", "NguoiXuatNavigation")
                        .WithMany("LichSuXuatBaoCaos")
                        .HasForeignKey("NguoiXuat")
                        .HasConstraintName("FK_NhanVienBaoCao");

                    b.Navigation("NguoiXuatNavigation");
                });

            modelBuilder.Entity("GymAPI.Models.LichTap", b =>
                {
                    b.HasOne("GymAPI.Models.Hlv", "MaHlvNavigation")
                        .WithMany("LichTaps")
                        .HasForeignKey("MaHlv")
                        .HasConstraintName("maHLV_FK_LichTap");

                    b.HasOne("GymAPI.Models.HoiVien", "MaHvNavigation")
                        .WithMany("LichTaps")
                        .HasForeignKey("MaHv")
                        .HasConstraintName("maHV_FK_Lichtap");

                    b.Navigation("MaHlvNavigation");

                    b.Navigation("MaHvNavigation");
                });

            modelBuilder.Entity("GymAPI.Models.GoiTap", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("GymAPI.Models.Hlv", b =>
                {
                    b.Navigation("LichTaps");
                });

            modelBuilder.Entity("GymAPI.Models.HoiVien", b =>
                {
                    b.Navigation("HopDongs");

                    b.Navigation("LichTaps");
                });

            modelBuilder.Entity("GymAPI.Models.HopDong", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("GymAPI.Models.NhanVien", b =>
                {
                    b.Navigation("LichSuXuatBaoCaos");
                });
#pragma warning restore 612, 618
        }
    }
}
